services:
  - type: web
    name: hummingwallet-server
    runtime: docker
    plan: free
    buildCommand: swift build -c release
    startCommand: swift run -c release
    envVars:
      - key: SWIFT_BACKTRACE
        value: enable=yes
    healthCheckPath: /health